//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTest.LemonWayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LemonWayService.LemonWayServiceSoap")]
    public interface LemonWayServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Fibonacci(int baseNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<int> FibonacciAsync(int baseNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FibonacciWithError", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TechnicalTest.LemonWayService.FibonacciResult FibonacciWithError(int baseNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FibonacciWithError", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalTest.LemonWayService.FibonacciResult> FibonacciWithErrorAsync(int baseNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string XmlToJson(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<string> XmlToJsonAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJsonWithError", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TechnicalTest.LemonWayService.XmlToJsonResut XmlToJsonWithError(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJsonWithError", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalTest.LemonWayService.XmlToJsonResut> XmlToJsonWithErrorAsync(string xml);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FibonacciResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonResut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LemonWayServiceSoapChannel : TechnicalTest.LemonWayService.LemonWayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LemonWayServiceSoapClient : System.ServiceModel.ClientBase<TechnicalTest.LemonWayService.LemonWayServiceSoap>, TechnicalTest.LemonWayService.LemonWayServiceSoap {
        
        public LemonWayServiceSoapClient() {
        }
        
        public LemonWayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LemonWayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Fibonacci(int baseNumber) {
            return base.Channel.Fibonacci(baseNumber);
        }
        
        public System.Threading.Tasks.Task<int> FibonacciAsync(int baseNumber) {
            return base.Channel.FibonacciAsync(baseNumber);
        }
        
        public TechnicalTest.LemonWayService.FibonacciResult FibonacciWithError(int baseNumber) {
            return base.Channel.FibonacciWithError(baseNumber);
        }
        
        public System.Threading.Tasks.Task<TechnicalTest.LemonWayService.FibonacciResult> FibonacciWithErrorAsync(int baseNumber) {
            return base.Channel.FibonacciWithErrorAsync(baseNumber);
        }
        
        public string XmlToJson(string xml) {
            return base.Channel.XmlToJson(xml);
        }
        
        public System.Threading.Tasks.Task<string> XmlToJsonAsync(string xml) {
            return base.Channel.XmlToJsonAsync(xml);
        }
        
        public TechnicalTest.LemonWayService.XmlToJsonResut XmlToJsonWithError(string xml) {
            return base.Channel.XmlToJsonWithError(xml);
        }
        
        public System.Threading.Tasks.Task<TechnicalTest.LemonWayService.XmlToJsonResut> XmlToJsonWithErrorAsync(string xml) {
            return base.Channel.XmlToJsonWithErrorAsync(xml);
        }
    }
}
